/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClienteFormDialog: typeof import('./components/ClienteFormDialog.vue')['default']
    ConfirmaExclusao: typeof import('./components/common/ConfirmaExclusao.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MaterialFormDialog: typeof import('./components/MaterialFormDialog.vue')['default']
    MaterialSelectDialog: typeof import('./components/MaterialSelectDialog.vue')['default']
    MenuAcoes: typeof import('./components/common/MenuAcoes.vue')['default']
    ProdutoFormDialog: typeof import('./components/ProdutoFormDialog.vue')['default']
    Remove: typeof import('./components/Remove.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
