export const CODIGOS_ERRO = {
     ERRO_INTERNO: { codigo: 1000, mensagem: 'Erro interno do servidor' },
     DADOS_INCOMPLETOS: { codigo: 1001, mensagem: 'Preencha todos os dados necessários' },
     DADO_TIPO_INVALIDO: { codigo: 1002, mensagem: 'O tipo do dado enviado é inválido' },
     ID_INVALIDO: { codigo: 1003, mensagem: 'O ID enviado é inválido' },
     CODIGO_INVALIDO: { codigo: 1004, mensagem: 'O Código enviado é inválido' },
     MINUTOS_INVALIDOS: { codigo: 1005, mensagem: 'Os minutos enviados são inválidos' },
     HORAS_INVALIDAS: { codigo: 1006, mensagem: 'As horas enviadas são inválidas' },

     CLIENTE_LISTAR_ERR: { codigo: 1100, mensagem: 'Erro ao listar clientes' },
     CLIENTE_EXISTE_ERR: { codigo: 1101, mensagem: 'O Cliente já está registrado.' },
     CLIENTE_EXISTE_IG_ERR: { codigo: 1101.1, mensagem: 'Já existe um cliente com esse instagram registrado.' },
     CLIENTE_EXISTE_TEL_ERR: { codigo: 1101.2, mensagem: 'Já existe um cliente com esse telefone registrado.' },
     CLIENTE_N_EXISTE_ERR: { codigo: 1102, mensagem: 'O Cliente não existe.' },

     ENCOMENDA_LIST_ERR: { codigo: 1201, mensagem: 'Erro ao listar encomendas.' },
     ENCOMENDA_CRIAR_ERR: { codigo: 1202, mensagem: 'Erro ao criar encomenda.' },
     ENCOMENDA_EDITAR_ERR: { codigo: 1203, mensagem: 'Erro ao editar encomenda.' },
     ENCOMENDA_EXCLUIR_ERR: { codigo: 1204, mensagem: 'Erro ao excluir encomenda.' },
     ENCOMENDA_N_EXISTE_ERR: { codigo: 1205, mensagem: 'A encomenda não existe.' },

     PRODUTO_LIST_ERR: { codigo: 1301, mensagem: 'Erro ao listar produtos.' },
     PRODUTO_CRIAR_ERR: { codigo: 1302, mensagem: 'Erro ao criar produto.' },
     PRODUTO_EDITAR_ERR: { codigo: 1303, mensagem: 'Erro ao editar produto.' },
     PRODUTO_EXCLUIR_ERR: { codigo: 1304, mensagem: 'Erro ao criar produto.' },
     PRODUTO_N_EXISTE_ERR: { codigo: 1305, mensagem: 'O produto não existe.' },

     MATERIAL_LIST_ERR: { codigo: 1401, mensagem: 'Erro ao listar materiais.' },
     MATERIAL_CRIAR_ERR: { codigo: 1402, mensagem: 'Erro ao criar material.' },
     MATERIAL_EDITAR_ERR: { codigo: 1403, mensagem: 'Erro ao editar material.' },
     MATERIAL_EXCLUIR_ERR: { codigo: 1404, mensagem: 'Erro ao excluir material.' },
     MATERIAL_N_EXISTE_ERR: { codigo: 1405, mensagem: 'O material não existe.' },

     PRODUTO_MATERIAL_LISTAR_ERRO: { codigo: 1500, mensagem: 'Erro ao listar Materiais do Produto.' },
     PRODUTO_MATERIAL_EXISTE_ERRO: { codigo: 1501, mensagem: 'Erro ao verificar se o produto ou material já está registrado.' },
     PRODUTO_MATERIAL_N_EXISTE_ERRO: { codigo: 1502, mensagem: 'Erro ao verificar se o produto ou material existe.' },
     PRODUTO_MATERIAL_CRIAR_ERRO: { codigo: 1503, mensagem: 'Erro ao criar produto ou material.' },
     PRODUTO_MATERIAL_EDITAR_ERRO: { codigo: 1504, mensagem: 'Erro ao editar produto ou material.' },
     PRODUTO_MATERIAL_EXCLUIR_ERRO: { codigo: 1505, mensagem: 'Erro ao excluir produto ou material.' },
     PRODUTO_MATERIAL_N_CORRESPONDE_ERRO: { codigo: 1506, mensagem: 'O Material lançado não corresponde ao produto.' },

     ENCOMENDA_MATERIAL_LISTAR_ERRO: { codigo: 1600, mensagem: 'Erro ao listar encomendas de materiais.' },
     ENCOMENDA_MATERIAL_EXISTE_ERRO: { codigo: 1601, mensagem: 'Erro ao verificar se a encomenda de material já está registrada.' },
     ENCOMENDA_MATERIAL_N_EXISTE_ERRO: { codigo: 1602, mensagem: 'O material não existe.' },
     ENCOMENDA_MATERIAL_CRIAR_ERRO: { codigo: 1603, mensagem: 'Erro ao criar encomenda de material.' },
     ENCOMENDA_MATERIAL_EDITAR_ERRO: { codigo: 1604, mensagem: 'Erro ao editar encomenda de material.' },
     ENCOMENDA_MATERIAL_EXCLUIR_ERRO: { codigo: 1605, mensagem: 'Erro ao excluir encomenda de material.' },
     ENCOMENDA_MATERIAL_N_CORRESPONDE_ERRO: { codigo: 1606, mensagem: 'O material informado não corresponde à encomenda.' },
}
export const CODIGOS_SUCESSO = {
     SUCESSO_GENERICO: { codigo: 2000, mensagem: 'Erro interno do servidor' },

     CLIENTE_LISTAR_SUCESS: { codigo: 2100, mensagem: 'Clientes listados com sucesso.' },
     CLIENTE_EXISTE_SUCESS: { codigo: 2101, mensagem: 'O Cliente já está registrado.' },
     CLIENTE_N_EXISTE_SUCESS: { codigo: 2102, mensagem: 'O Cliente não existe.' },
     CLIENTE_CRIAR_SUCESS: { codigo: 2103, mensagem: 'Cliente criado com sucesso.' },
     CLIENTE_EDITAR_SUCESS: { codigo: 2104, mensagem: 'Cliente editado com sucesso.' },
     CLIENTE_EXCLUIR_SUCESS: { codigo: 2105, mensagem: 'Cliente excluido com sucesso.' },

     ENCOMENDA_LISTAR_SUCESS: { codigo: 2200, mensagem: 'Encomendas listadas com sucesso.' },
     ENCOMENDA_EXISTE_SUCESS: { codigo: 2201, mensagem: 'A Encomenda já está registrado.' },
     ENCOMENDA_N_EXISTE_SUCESS: { codigo: 2202, mensagem: 'A Encomenda não existe.' },
     ENCOMENDA_CRIAR_SUCESS: { codigo: 2203, mensagem: 'Encomenda criada com sucesso.' },
     ENCOMENDA_EDITAR_SUCESS: { codigo: 2204, mensagem: 'Encomenda editada com sucesso.' },
     ENCOMENDA_EXCLUIR_SUCESS: { codigo: 2205, mensagem: 'Encomenda excluida com sucesso.' },

     PRODUTO_LISTAR_SUCESS: { codigo: 2300, mensagem: 'Produto listados com sucesso.' },
     PRODUTO_EXISTE_SUCESS: { codigo: 2301, mensagem: 'O Produto já está registrado.' },
     PRODUTO_N_EXISTE_SUCESS: { codigo: 2302, mensagem: 'O Produto não existe.' },
     PRODUTO_CRIAR_SUCESS: { codigo: 2303, mensagem: 'Produto criado com sucesso.' },
     PRODUTO_EDITAR_SUCESS: { codigo: 2304, mensagem: 'Produto editado com sucesso.' },
     PRODUTO_EDITAR_FOTOS_SUCESS: { codigo: 2305, mensagem: 'Fotos do produto editadas com sucesso.' },
     PRODUTO_EXCLUIR_SUCESS: { codigo: 2306, mensagem: 'Produto excluido com sucesso.' },
     PRODUTO_LISTAR_FOTOS_SUCESS: { codigo: 2307, mensagem: 'Produto excluido com sucesso.' },

     MATERIAL_LISTAR_SUCESS: { codigo: 2400, mensagem: 'Materiais listados com sucesso.' },
     MATERIAL_EXISTE_SUCESS: { codigo: 2401, mensagem: 'O material já está registrado.' },
     MATERIAL_N_EXISTE_SUCESS: { codigo: 2402, mensagem: 'O material não existe.' },
     MATERIAL_CRIAR_SUCESS: { codigo: 2403, mensagem: 'Material criado com sucesso.' },
     MATERIAL_EDITAR_SUCESS: { codigo: 2404, mensagem: 'Material editado com sucesso.' },
     MATERIAL_EXCLUIR_SUCESS: { codigo: 2405, mensagem: 'Material excluído com sucesso.' },

     PRODUTO_MATERIAL_LISTAR_SUCESS: { codigo: 2500, mensagem: 'Materiais do Produto listados com sucesso.' },
     PRODUTO_MATERIAL_EXISTE_SUCESS: { codigo: 2501, mensagem: 'Material do produto já está registrado.' },
     PRODUTO_MATERIAL_N_EXISTE_SUCESS: { codigo: 2502, mensagem: 'O material do produto não existe.' },
     PRODUTO_MATERIAL_CRIAR_SUCESS: { codigo: 2503, mensagem: 'Material do produto criado com sucesso.' },
     PRODUTO_MATERIAL_EDITAR_SUCESS: { codigo: 2504, mensagem: 'Material do produto editado com sucesso.' },
     PRODUTO_MATERIAL_EXCLUIR_SUCESS: { codigo: 2505, mensagem: 'Material do produto excluído com sucesso.' },

     ENCOMENDA_MATERIAL_LISTAR_SUCCESS: { codigo: 2600, mensagem: 'Materiais da encomenda listadas com sucesso.' },
     ENCOMENDA_MATERIAL_EXISTE_SUCCESS: { codigo: 2601, mensagem: 'Materiais da encomenda verificada com sucesso.' },
     ENCOMENDA_MATERIAL_N_EXISTE_SUCCESS: { codigo: 2602, mensagem: 'Material da encomenda não encontrada.' },
     ENCOMENDA_MATERIAL_CRIAR_SUCCESS: { codigo: 2603, mensagem: 'Material da encomenda criada com sucesso.' },
     ENCOMENDA_MATERIAL_EDITAR_SUCCESS: { codigo: 2604, mensagem: 'Material da encomenda editada com sucesso.' },
     ENCOMENDA_MATERIAL_EXCLUIR_SUCCESS: { codigo: 2605, mensagem: 'Material da encomenda excluída com sucesso.' },
     ENCOMENDA_MATERIAL_CORRESPONDE_SUCCESS: { codigo: 2606, mensagem: 'Material corresponde à encomenda.' },
     
     TIPO_MATERIAL_LISTAR_SUCESS: { codigo: 2700, mensagem: 'Tipos de materiais listados com sucesso.' },
     UNIDADE_MEDIDA_LISTAR_SUCESS: { codigo: 2701, mensagem: 'Unidades de medidas listadas com sucesso.' },
}


